# Use an existing secret that has your Docker registry credentials:
#
#global:
#  image:
#    imagePullSecrets:
#      - name: flagsmithofficial-example-pull-secret

serviceMonitor:
  enabled: true

api:
  livenessProbe:
    exec:
      command:
      - /usr/bin/python
      - -c
      - |
        import socket
        sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
        sock.settimeout(1)
        sock.connect(('localhost', 8000))
        sock.close()
  image:
    repository: quay.io/flagsmithofficial/flagsmith-enterprise-api
  extraEnv:
    USE_SECURE_COOKIES: false
    LOG_FORMAT: json
    ACCESS_LOG_LOCATION: '-'
    ACCESS_LOG_EXTRA_ITEMS: '{flagsmith.environment_id}e'

taskProcessor:
  image:
    repository: quay.io/flagsmithofficial/flagsmith-enterprise-api
  enabled: true
  extraEnv:
    ACCESS_LOG_LOCATION: '-'
    ACCESS_LOG_FORMAT: json
    TASK_PROCESSOR_NUM_THREADS: 5

frontend:
  image:
    repository: quay.io/flagsmithofficial/flagsmith-frontend
  extraEnv:
    USE_SECURE_COOKIES: false

postgresql:
  enabled: true
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true

influxdb2:
  enabled: false
