{
 "title": "Flagsmith API and task processor",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource_prometheus", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Scraped pods per service/version",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "count by(service, version) (flagsmith_build_info)",
     "legendFormat": "{{ service }} {{ version }}"
    },
    { "legendFormat": "__auto" }
   ]
  },
  { "title": "HTTP request rate", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Reads by status code",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(method, response_status) (rate(flagsmith_http_server_requests_total{method=~\"GET|HEAD\",route!=\"\",response_status=~\"[1-4]..\"}[$__rate_interval]))",
     "legendFormat": "{{method}} {{response_status}}"
    }
   ]
  },
  {
   "title": "Error reads by status code",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(method, response_status) (rate(flagsmith_http_server_requests_total{method=\"GET\",route!=\"\",response_status=~\"5..\"}[$__rate_interval])) or vector(0)",
     "legendFormat": "{{method}}  {{response_status}} "
    }
   ]
  },
  {
   "title": "Writes by status code",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(method, response_status) (rate(flagsmith_http_server_requests_total{method!=\"GET\",route!=\"\"}[$__rate_interval])) or vector(0)",
     "legendFormat": "{{method}}  {{response_status}} "
    }
   ]
  },
  {
   "title": "Error writes by status code",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(method, response_status) (rate(flagsmith_http_server_requests_total{method!=\"GET\",route!=\"\",response_status=~\"5..\"}[$__rate_interval])) or vector(0)",
     "legendFormat": "{{method}}  {{response_status}} "
    }
   ]
  },
  {
   "title": "Reads by route",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(method, route) (rate(flagsmith_http_server_requests_total{method=\"GET\",route!=\"\"}[$__rate_interval]))",
     "legendFormat": "{{method}} {{route}}"
    }
   ]
  },
  {
   "title": "Writes by route",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(method, route) (rate(flagsmith_http_server_requests_total{method!=\"GET\",route!=\"\"}[$__rate_interval])) or vector(0)",
     "legendFormat": "{{method}} {{route}}"
    }
   ]
  },
  {
   "title": "All requests and status codes",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(flagsmith_http_server_requests_total{route!=\"\"}[$__rate_interval])) by(method, response_status, route)",
     "legendFormat": "{{method}}  {{response_status}} {{route}}"
    }
   ]
  },
  { "title": "HTTP request duration", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 } },
  {
   "title": "p95 read duration by route",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(flagsmith_http_server_request_duration_seconds_bucket{route!=\"\",method=\"GET\"}[$__rate_interval])) by (le, route, method))",
     "legendFormat": "{{method}} {{route}}"
    }
   ]
  },
  {
   "title": "p95 write duration by route",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(flagsmith_http_server_request_duration_seconds_bucket{route!=\"\",method!=\"GET\"}[$__rate_interval])) by (le, route, method)) or vector(0)",
     "legendFormat": "{{method}} {{route}}"
    }
   ]
  },
  {
   "title": "p95 read duration by status",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(flagsmith_http_server_request_duration_seconds_bucket{route!=\"\",method=\"GET\"}[$__rate_interval])) by (le, response_status))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "p50 write duration by status",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(flagsmith_http_server_request_duration_seconds_bucket{route!=\"\",method!=\"GET\"}[$__rate_interval])) by (le, response_status)) or vector(0)",
     "legendFormat": "{{response_status}}"
    }
   ]
  },
  { "title": "Task metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 66 } },
  {
   "title": "Enqueued tasks",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 67 },
   "targets": [
    {
     "expr": "sum(\n  increase(\n    flagsmith_task_processor_enqueued_tasks_total[$__rate_interval]\n  )\n) by (task_identifier)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Task duration",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(flagsmith_task_processor_task_duration_seconds_bucket[$__rate_interval])) by (le, result))",
     "legendFormat": "p95 {{result}}"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(flagsmith_task_processor_task_duration_seconds_bucket[$__rate_interval])) by (le, result))",
     "legendFormat": "p50 {{result}}"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(flagsmith_task_processor_task_duration_seconds_bucket[$__rate_interval])) by (le, result))",
     "legendFormat": "p99 {{result}}"
    }
   ]
  },
  {
   "title": "Failed tasks",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 67 },
   "targets": [
    {
     "expr": "sum(\n  increase(\n    flagsmith_task_processor_finished_tasks_total{result!=\"success\"}[$__rate_interval]\n  )\n) by (task_identifier)\n\nor vector(0)",
     "legendFormat": "{{task_identifier}}"
    }
   ]
  },
  {
   "title": "Completed tasks",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 76 },
   "targets": [
    {
     "expr": "sum(\n  increase(\n    flagsmith_task_processor_finished_tasks_total{result=\"success\"}[$__rate_interval]\n  )\n) by (task_identifier)",
     "legendFormat": "{{task_identifier}}"
    }
   ]
  },
  {
   "title": "p95 duration by task",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 85 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(flagsmith_task_processor_task_duration_seconds_bucket[$__rate_interval])) by (le, task_identifier))",
     "legendFormat": "{{task_identifier}}"
    }
   ]
  }
 ]
}