api:
  extraEnv:
    USE_SECURE_COOKIES: false
    ACCESS_LOG_LOCATION: '-'
taskProcessor:
  enabled: true
  extraEnv:
    ACCESS_LOG_LOCATION: '-'
frontend:
  extraEnv:
    USE_SECURE_COOKIES: false
postgresql:
  enabled: true
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
influxdb2:
  enabled: false
