api:
  image:
    repository: flagsmith/flagsmith-private-cloud-api
  extraEnv:
    USE_SECURE_COOKIES: false
    PROMETHEUS_ENABLED: true
    ACCESS_LOG_LOCATION: '-'
  replicacount: 2

taskProcessor:
  enabled: true
  extraEnv:
    PROMETHEUS_ENABLED: true
    ACCESS_LOG_LOCATION: '-'
  replicacount: 2

frontend:
  extraEnv:
    USE_SECURE_COOKIES: false
  replicacount: 2

postgresql:
  enabled: true
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true

extraObjects:
  - apiVersion: monitoring.coreos.com/v1
    kind: ServiceMonitor
    metadata:
      name: flagsmith
    spec:
      jobLabel: app.kubernetes.io/name
      selector:
        matchExpressions:
          - { key: app.kubernetes.io/component, operator: In, values: [ api, task-processor ] }
      endpoints:
        - port: http
          interval: 15s
          path: /metrics

influxdb2:
  enabled: false
