repositories:
  - name: flagsmith
    url: https://flagsmith.github.io/flagsmith-charts
  - name: prometheus-community
    url: https://prometheus-community.github.io/helm-charts
  - name: grafana
    url: https://grafana.github.io/helm-charts

releases:
  - name: flagsmith-2-166-0
    namespace: flagsmith
    chart: flagsmith/flagsmith
    values:
      - api:
          image:
            tag: 2.166.0
      - postgresql:
          enabled: true
          metrics:
            enabled: true
            serviceMonitor:
              enabled: true
      - influxdb:
          enabled: false

  - name: flagsmith-prometheus
    namespace: flagsmith-prometheus
    chart: flagsmith/flagsmith
    values:
      - api:
          image:
            repository: ghcr.io/flagsmith/flagsmith-private-cloud
            tag: pr-5254
          extraEnv:
            PROMETHEUS_ENABLED: true
      - postgresql:
          enabled: true
          metrics:
            enabled: true
            serviceMonitor:
              enabled: true
      - influxdb:
          enabled: false

  - name: prometheus
    namespace: monitoring
    chart: prometheus-community/prometheus
    values:
      - server:
          extraScrapeConfigs: |
            - job_name: flagsmith
              static_configs:
                - targets:
                  - flagsmith-prometheus-api.flagsmith-prometheus.svc.cluster.local/metrics

  - name: grafana
    namespace: monitoring
    chart: grafana/grafana
    values:
      - persistence:
          enabled: true
          type: pvc
      - datasources:
          datasources.yaml:
            apiVersion: 1
            datasources:
              - name: Prometheus
                type: prometheus
                url: http://prometheus-server.monitoring.svc.cluster.local
                access: proxy
                isDefault: true
              - name: PostgreSQL 2.166.0
                type: postgres
                url: flagsmith-2-166-0-dev-postgresql.flagsmith.svc.cluster.local:5432
                database: flagsmith
                user: postgres
                secureJsonData:
                  password: flagsmith
                jsonData:
                  sslmode: disable
              - name: PostgreSQL Prometheus
                type: postgres
                url: flagsmith-prometheus-dev-postgresql.flagsmith-prometheus.svc.cluster.local:5432
                database: flagsmith
                user: postgres
                secureJsonData:
                  password: flagsmith
                jsonData:
                  sslmode: disable
      - grafana.ini:
          auth.anonymous:
            enabled: true
            org_role: Admin 
          server:
            domain: "localhost"
            root_url: "%(protocol)s://%(domain)s:%(http_port)s/"
            serve_from_sub_path: false
          dashboards:
            default_home_dashboard_path: /var/lib/grafana/dashboards/flagsmith/flagsmith-overview.json
      - dashboardProviders:
          dashboardproviders.yaml:
            apiVersion: 1
            providers:
            - name: 'grafana-dashboards-kubernetes'
              orgId: 1
              folder: 'Kubernetes'
              type: file
              disableDeletion: true
              editable: true
              options:
                path: /var/lib/grafana/dashboards/grafana-dashboards-kubernetes
            - name: 'flagsmith-dashboards'
              orgId: 1
              folder: 'Flagsmith'
              type: file
              disableDeletion: false
              editable: true
              options:
                path: /var/lib/grafana/dashboards/flagsmith
      - dashboards:
          grafana-dashboards-kubernetes:
            k8s-system-api-server:
              url: https://raw.githubusercontent.com/dotdc/grafana-dashboards-kubernetes/master/dashboards/k8s-system-api-server.json
              token: ''
            k8s-system-coredns:
              url: https://raw.githubusercontent.com/dotdc/grafana-dashboards-kubernetes/master/dashboards/k8s-system-coredns.json
              token: ''
            k8s-views-global:
              url: https://raw.githubusercontent.com/dotdc/grafana-dashboards-kubernetes/master/dashboards/k8s-views-global.json
              token: ''
            k8s-views-namespaces:
              url: https://raw.githubusercontent.com/dotdc/grafana-dashboards-kubernetes/master/dashboards/k8s-views-namespaces.json
              token: ''
            k8s-views-nodes:
              url: https://raw.githubusercontent.com/dotdc/grafana-dashboards-kubernetes/master/dashboards/k8s-views-nodes.json
              token: ''
            k8s-views-pods:
              url: https://raw.githubusercontent.com/dotdc/grafana-dashboards-kubernetes/master/dashboards/k8s-views-pods.json
              token: ''
          flagsmith:
            flagsmith-overview:
              file: dashboards/flagsmith-overview.json
