repositories:
  - name: flagsmith
    url: https://flagsmith.github.io/flagsmith-charts
  - name: prometheus-community
    url: https://prometheus-community.github.io/helm-charts

releases:
  - name: prometheus
    namespace: monitoring
    chart: prometheus-community/kube-prometheus-stack
    values:
      - grafana-values.yaml.gotmpl
      - prometheus:
          prometheusSpec:
            serviceMonitorSelectorNilUsesHelmValues: false
      - kube-state-metrics:
          metricLabelsAllowlist:
            - deployments=[helm.sh/chart]

  - name: flagsmith
    namespace: flagsmith
    chart: ../charts/charts/flagsmith/
    version: 0.74.0
    needs:
      - monitoring/prometheus
    values:
      - flagsmith-values.yaml
