repositories:
  - name: flagsmith
    url: https://flagsmith.github.io/flagsmith-charts
  - name: prometheus-community
    url: https://prometheus-community.github.io/helm-charts
  - name: grafana
    url: https://grafana.github.io/helm-charts

releases:
  - name: flagsmith-2-166-0
    namespace: flagsmith-2-166-0
    chart: flagsmith/flagsmith
    values:
      - flagsmith-values.yaml
      - api:
          image:
            tag: 2.166.0

  - name: flagsmith-prometheus
    namespace: flagsmith-prometheus
    chart: flagsmith/flagsmith
    version: 0.72.0
    values:
      - flagsmith-values.yaml
      - api:
          image:
            repository: flagsmith/flagsmith-private-cloud-api
            tag: 2.170.0
          extraEnv:
            PROMETHEUS_ENABLED: true

  - name: prometheus
    namespace: monitoring
    chart: prometheus-community/prometheus
    values:
      - prometheus-values.yaml

  - name: grafana
    namespace: monitoring
    chart: grafana/grafana
    values:
      - grafana-values.yaml
